name: Comment on Github PR 🔊  
description: This action would install Python and run a script to comment on a Github PR.

# Define the inputs needed for the action
inputs:
  filename:
    description: File to read the comments to install
    required: true
  github_token:
    description: Github token to access to all the API endpoint
    required: true

# Define the steps
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Install Python 🐍
      uses: actions/setup-python@v4
      id: pipenv
      with:
        python-version: 3.10
        cache: 'pip'

    - name: Install packages 🏗️
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -Iv PyGithub==1.58.1

    - name: Comment on the PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        FILENAME: ${{ inputs.filename }}
      run: |
        python .github/utilities/comment_pr.py
